/**
 * Summaries of api_calls for dx/metrics.md (DX_PROTOCOL §3.2): per endpoint and per region
 * call counts, error rates, p50/p95 latency and envelope-code distribution.
 */
import type { ApiCallRecord } from './telemetry.js';

const SUCCESS_CODES = new Set(['0', '000000000']);

/** Success = an HTTP response below 400 whose envelope code is the module's success code. */
export function isSuccess(record: ApiCallRecord): boolean {
  return (
    record.httpStatus !== null &&
    record.httpStatus < 400 &&
    record.code !== null &&
    SUCCESS_CODES.has(record.code)
  );
}

/** Nearest-rank percentile of an ascending list (p in 0–100). */
export function percentile(sorted: readonly number[], p: number): number | null {
  if (sorted.length === 0) return null;
  const rank = Math.max(1, Math.ceil((p / 100) * sorted.length));
  return sorted[rank - 1] ?? null;
}

export interface CallStats {
  calls: number;
  errors: number;
  p50Ms: number | null;
  p95Ms: number | null;
}

function stats(records: readonly ApiCallRecord[]): CallStats {
  const latencies = records.map((r) => r.latencyMs).sort((a, b) => a - b);
  return {
    calls: records.length,
    errors: records.filter((r) => !isSuccess(r)).length,
    p50Ms: percentile(latencies, 50),
    p95Ms: percentile(latencies, 95),
  };
}

function groupBy<K extends string>(
  records: readonly ApiCallRecord[],
  key: (r: ApiCallRecord) => K,
) {
  const groups = new Map<K, ApiCallRecord[]>();
  for (const record of records) {
    const k = key(record);
    groups.set(k, [...(groups.get(k) ?? []), record]);
  }
  return [...groups.entries()].sort(([a], [b]) => a.localeCompare(b));
}

function codeLabel(record: ApiCallRecord): string {
  if (record.httpStatus === null) return 'no response';
  return record.code ?? `HTTP ${record.httpStatus}`;
}

const ms = (value: number | null) => (value === null ? '—' : String(value));
const pct = (part: number, whole: number) =>
  whole === 0 ? '—' : `${((part / whole) * 100).toFixed(1)}%`;
const cell = (text: string) => text.replaceAll('|', '\\|').replaceAll('\n', ' ');

export interface MetricsMeta {
  generatedAt: Date;
  since: Date | null;
}

export function renderMetricsMarkdown(
  records: readonly ApiCallRecord[],
  meta: MetricsMeta,
): string {
  const first = records[0]?.ts;
  const last = records.at(-1)?.ts;
  const lines = [
    '# dx/metrics.md — Binance Web3 API call metrics (generated)',
    '',
    `> Generated by \`pnpm dx:metrics\` at ${meta.generatedAt.toISOString()} from the \`api_calls\` table: ` +
      `${records.length} HTTP attempts${first ? `, ${first} → ${last}` : ''}` +
      `${meta.since ? ` (since ${meta.since.toISOString()})` : ''}.`,
    '> Method: one row per HTTP attempt (429 retries included). Latency is measured on the calling host',
    '> from request start to the full body read. p50/p95 use the nearest-rank method. An error is no',
    '> response, HTTP >= 400, or an envelope code other than success (`0`, B402 `000000000`).',
    '',
    '## By endpoint',
    '',
    '| Module | Endpoint | Calls | Errors | Error rate | p50 ms | p95 ms | Codes (count) |',
    '| --- | --- | --: | --: | --: | --: | --: | --- |',
  ];
  for (const [, group] of groupBy(records, (r) => `${r.module} ${r.endpoint}`)) {
    const s = stats(group);
    const codes = groupBy(group, codeLabel)
      .map(([code, rows]) => `${code} ×${rows.length}`)
      .join(', ');
    const { module, endpoint } = group[0]!;
    lines.push(
      `| ${module} | ${endpoint} | ${s.calls} | ${s.errors} | ${pct(s.errors, s.calls)} | ${ms(s.p50Ms)} | ${ms(s.p95Ms)} | ${codes} |`,
    );
  }

  lines.push(
    '',
    '## By region',
    '',
    '| Region | Calls | Errors | p50 ms | p95 ms |',
    '| --- | --: | --: | --: | --: |',
  );
  for (const [region, group] of groupBy(records, (r) => r.region ?? 'unset')) {
    const s = stats(group);
    lines.push(`| ${region} | ${s.calls} | ${s.errors} | ${ms(s.p50Ms)} | ${ms(s.p95Ms)} |`);
  }

  const failures = records.filter((r) => !isSuccess(r));
  lines.push('', '## Error codes', '');
  if (failures.length === 0) {
    lines.push('No failed calls recorded.');
  } else {
    lines.push(
      '| Module | Code | Count | Last seen | Last message (masked) |',
      '| --- | --- | --: | --- | --- |',
    );
    for (const [, group] of groupBy(failures, (r) => `${r.module} ${codeLabel(r)}`)) {
      const latest = group.at(-1)!;
      lines.push(
        `| ${latest.module} | ${codeLabel(latest)} | ${group.length} | ${latest.ts} | ${cell(latest.msg ?? '')} |`,
      );
    }
  }
  return `${lines.join('\n')}\n`;
}
