import path from 'node:path';
import { fileURLToPath } from 'node:url';
import type { ApiCallRecord, ApiCallSink, ApiModule } from '@ijaro/binance';
import { asc, desc, getTableColumns, gte, sql as rawSql } from 'drizzle-orm';
import { drizzle } from 'drizzle-orm/postgres-js';
import { migrate } from 'drizzle-orm/postgres-js/migrator';
import postgres from 'postgres';
import { apiCalls, instruments, tapeSamples } from './schema.js';

export { apiCalls, instruments, tapeSamples };

export type InstrumentRow = typeof instruments.$inferSelect;
export type TapeSampleInsert = typeof tapeSamples.$inferInsert;
export type TapeSampleRow = typeof tapeSamples.$inferSelect;

const MIGRATIONS = path.join(path.dirname(fileURLToPath(import.meta.url)), '..', 'drizzle');

export function createDb(databaseUrl: string) {
  const sql = postgres(databaseUrl, { max: 5, onnotice: () => undefined });
  const db = drizzle(sql);
  return { db, close: () => sql.end({ timeout: 5 }) };
}

export type Db = ReturnType<typeof createDb>['db'];

export async function migrateDb(db: Db): Promise<void> {
  await migrate(db, { migrationsFolder: MIGRATIONS });
}

export async function insertApiCall(db: Db, record: ApiCallRecord): Promise<void> {
  await db.insert(apiCalls).values(record);
}

/** The Binance client's `onApiCall` hook, backed by Postgres. */
export function createApiCallSink(db: Db): ApiCallSink {
  return (record) => insertApiCall(db, record);
}

export async function listApiCalls(db: Db, since?: Date): Promise<ApiCallRecord[]> {
  const rows = await db
    .select()
    .from(apiCalls)
    .where(since ? gte(apiCalls.ts, since.toISOString()) : undefined)
    .orderBy(asc(apiCalls.ts), asc(apiCalls.id));
  return rows.map(({ id: _id, ...row }) => ({
    ...row,
    ts: new Date(row.ts).toISOString(),
    module: row.module as ApiModule,
  }));
}

/** Replaces the rows for the given ids: the registry is regenerated by `pnpm registry`, never hand-edited. */
export async function upsertInstruments(db: Db, rows: InstrumentRow[]): Promise<void> {
  if (rows.length === 0) return;
  const { id: _id, ...columns } = getTableColumns(instruments);
  const set = Object.fromEntries(
    Object.entries(columns).map(([key, column]) => [key, rawSql.raw(`excluded.${column.name}`)]),
  );
  await db.insert(instruments).values(rows).onConflictDoUpdate({ target: instruments.id, set });
}

export async function listInstruments(db: Db): Promise<InstrumentRow[]> {
  return db.select().from(instruments).orderBy(asc(instruments.ticker), asc(instruments.issuer));
}

export async function insertTapeSamples(db: Db, rows: TapeSampleInsert[]): Promise<void> {
  if (rows.length === 0) return;
  await db.insert(tapeSamples).values(rows);
}

/** Rows of the most recent tape run. */
export async function latestTapeSamples(db: Db): Promise<TapeSampleRow[]> {
  const [last] = await db
    .select({ sampledAt: tapeSamples.sampledAt })
    .from(tapeSamples)
    .orderBy(desc(tapeSamples.sampledAt))
    .limit(1);
  if (!last) return [];
  return db
    .select()
    .from(tapeSamples)
    .where(gte(tapeSamples.sampledAt, last.sampledAt))
    .orderBy(asc(tapeSamples.instrumentId), asc(tapeSamples.sizeUsd));
}
