/**
 * Drizzle schema. M0 ships `api_calls` (SPEC §3.1 item 2, §10), `instruments` (M0-05) and
 * `tape_samples` (M0-08); the other tables of SPEC §4
 * arrive with M1-01.
 */
import {
  bigserial,
  boolean,
  index,
  integer,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
} from 'drizzle-orm/pg-core';

/** One row per HTTP attempt to the Binance Web3 API, written by the client's onApiCall hook. */
export const apiCalls = pgTable(
  'api_calls',
  {
    id: bigserial('id', { mode: 'number' }).primaryKey(),
    /** X-OC-TIMESTAMP sent with the request (what Binance support asks for). */
    ts: timestamp('ts', { withTimezone: true, mode: 'string' }).notNull(),
    region: text('region'),
    module: text('module').notNull(),
    endpoint: text('endpoint').notNull(),
    method: text('method').notNull(),
    httpStatus: integer('http_status'),
    /** Envelope code as text: OC codes are numbers, B402 codes are strings. */
    code: text('code'),
    /** Masked: keys redacted, addresses shortened. */
    msg: text('msg'),
    latencyMs: integer('latency_ms').notNull(),
    requestId: text('request_id'),
    retryCount: integer('retry_count').notNull().default(0),
    fixturePath: text('fixture_path'),
  },
  (table) => [
    index('api_calls_ts_idx').on(table.ts),
    index('api_calls_endpoint_idx').on(table.module, table.endpoint),
  ],
);

/**
 * Instrument registry (SPEC §4 `Instrument`, DECISIONS D-07): generated by `pnpm registry` from the
 * RWA Data API and verified on-chain. Stock token addresses live only here, never in code.
 */
export const instruments = pgTable(
  'instruments',
  {
    /** `<ticker>:<issuer>`, e.g. `NVDA:bstocks`. */
    id: text('id').primaryKey(),
    ticker: text('ticker').notNull(),
    /** SPEC §4 `Issuer`: 'bstocks' | 'ondo' | 'xstocks' (API platformId `bstock` → `bstocks`). */
    issuer: text('issuer').notNull(),
    platformId: text('platform_id').notNull(),
    chainId: integer('chain_id').notNull(),
    address: text('address').notNull(),
    symbol: text('symbol').notNull(),
    decimals: integer('decimals').notNull(),
    /** 1 = stock, 2 = pre-IPO, 3 = ETF (RWA list `assetType`). */
    assetType: integer('asset_type'),
    /** Token → share ratio as a decimal string: on-chain uiMultiplier for bStocks, API ratio otherwise. */
    multiplier: text('multiplier').notNull(),
    multiplierSource: text('multiplier_source').notNull(),
    /** API `tokenToShareRatio`, kept to detect disagreement with the on-chain value. */
    apiShareRatio: text('api_share_ratio'),
    verifiedAt: timestamp('verified_at', { withTimezone: true, mode: 'string' }).notNull(),
  },
  (table) => [index('instruments_ticker_idx').on(table.ticker)],
);

/**
 * Market tape (SPEC §10): every 10 minutes, per instrument and per quote size, the on-chain price,
 * the reference price, the market state and one Trading API quote (or its error code).
 */
export const tapeSamples = pgTable(
  'tape_samples',
  {
    id: bigserial('id', { mode: 'number' }).primaryKey(),
    /** Start of the tape run this row belongs to (one run = all instruments × sizes). */
    sampledAt: timestamp('sampled_at', { withTimezone: true, mode: 'string' }).notNull(),
    /**
     * Idempotency key of the run: the 10-minute wall-clock slot for scheduled runs (a restarted
     * worker re-running a slot inserts nothing), the exact start time for manual `tape:once`.
     */
    slotAt: timestamp('slot_at', { withTimezone: true, mode: 'string' }).notNull(),
    instrumentId: text('instrument_id').notNull(),
    /** Our own clock: regular | pre | post | overnight | weekend | holiday (US equities, ET). */
    session: text('session').notNull(),
    /** RWA list statusInfo, as returned. */
    openState: boolean('open_state'),
    marketStatus: text('market_status'),
    reasonCode: text('reason_code'),
    tokenPrice: text('token_price'),
    referencePrice: text('reference_price'),
    /** Independent US stock price per share (RWA Dynamic V2 stockInfo.price); null off-hours. */
    stockPrice: text('stock_price'),
    /** Why the stock price call failed, when it did. */
    stockPriceError: text('stock_price_error'),
    priceUpdatedAt: timestamp('price_updated_at', { withTimezone: true, mode: 'string' }),
    sizeUsd: integer('size_usd').notNull(),
    /** Output token amount in smallest units (quote `toTokenAmount`). */
    expectedOut: text('expected_out'),
    priceImpactPct: text('price_impact_pct'),
    vendor: text('vendor'),
    executionMode: text('execution_mode'),
    route: text('route'),
    errorCode: text('error_code'),
    errorMsg: text('error_msg'),
    latencyMs: integer('latency_ms'),
  },
  (table) => [
    index('tape_samples_sampled_at_idx').on(table.sampledAt),
    index('tape_samples_instrument_idx').on(table.instrumentId, table.sampledAt),
    uniqueIndex('tape_samples_slot_uq').on(table.slotAt, table.instrumentId, table.sizeUsd),
  ],
);
