/**
 * `pnpm --filter @yieldvest/rwa-lp abi`: writes src/abi.ts from the forge artifacts in out/ (run
 * `forge build` first; the script does). CI regenerates it and fails on a diff, so the TypeScript
 * side never drifts from the contracts.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import prettier from 'prettier';

const CONTRACTS = [
  ['RwaSessionHook', 'rwaSessionHookAbi'],
  ['RwaLiquidityVault', 'rwaLiquidityVaultAbi'],
  ['KeeperReferenceOracle', 'keeperReferenceOracleAbi'],
  ['NyseMarketCalendar', 'nyseMarketCalendarAbi'],
] as const;

const root = new URL('..', import.meta.url);
const target = fileURLToPath(new URL('src/abi.ts', root));

let code =
  '// Generated by src/gen-abi.ts from the forge artifacts. Do not edit; run `pnpm --filter @yieldvest/rwa-lp abi`.\n';
for (const [contract, name] of CONTRACTS) {
  const artifact = JSON.parse(
    readFileSync(fileURLToPath(new URL(`out/${contract}.sol/${contract}.json`, root)), 'utf8'),
  ) as { abi: unknown };
  code += `\nexport const ${name} = ${JSON.stringify(artifact.abi)} as const;\n`;
}
const options = await prettier.resolveConfig(target);
writeFileSync(target, await prettier.format(code, { ...options, filepath: target }));
console.log(`${CONTRACTS.length} ABIs → ${target}`);
